.gitignore, Cargo.lock, Cargo.toml, README.md, src/config.rs, src/login.rs, src/main.rs
Made config.toml path dependent on the user's config directory instead of using the current directory.
=> Proper configuration paths

Cargo.lock, Cargo.toml, README.md, src/client.rs
Adds support for solving captchas by displaying the captcha image in the terminal and making the user solve it.
closes #6
=> Solve captchas

Cargo.lock, Cargo.toml, src/gpa.rs, src/main.rs, src/score_mapping_configs.json, src/semester.rs, src/subject.rs
Currently you can only see the score for each subject but you cannot see the letter grade or GPA unlike on the website.
=> Add letter grade and GPA

Cargo.toml, README.md
Added information to Cargo.toml and changed install instructions to install from crates.io
=> Publish to crates.io

src/config.rs, src/main.rs
Print messages when fetching something
=> Added status messages for fetching

Cargo.lock, Cargo.toml, src/main.rs
The colors used for each grade might be confusing, so the colors may be changed.
=> Added colors to scores

Cargo.lock, Cargo.toml, src/main.rs
Made subject scores and other information output in a table
=> Table output of subjects

Cargo.lock, Cargo.toml, src/main.rs, src/subject.rs
Made these run asynchronously
- get_gpa()
- get_elective_class_ids()
=> perf: run more things asynchronously

.github/workflows/release.yml, Cargo.toml, README.md, wix/main.wxs
Uses cargo-dist to setup CI to build precompiled binaries using github actions
=> Build precompiled binaries

src/gpa.rs, src/main.rs, src/subject.rs
It is better to know unweighted GPA as well, according to Hester.
=> feat(gpa): add unweighted gpa calculations

README.md, src/gpa.rs, src/main.rs
GPA Delta is the change in GPA when the grade of a subject increases or drops (when not changing to or from F).
For example, if English increases from A to A+, GPA Delta would be the resulting change in GPA.
=> Add GPA Delta

src/main.rs, src/subject.rs
=> fix: adjust subject weights so they sum up to 100

src/gpa.rs, src/main.rs, src/subject.rs
Allow user to view the highest GPA score can be obtained
=> Feature GPA full score calculate

Cargo.lock, Cargo.toml, src/main.rs
=> build: upgrade all dependencies

README.md, src/main.rs, src/subject.rs
- Added colorization of task scores
- Improved decimal place formatting.
- Added tasks feature to README
- Indented nested weights
=> Better format of tasks

Cargo.lock, Cargo.toml, src/main.rs
=> feat: init logger

README.md, flake.nix
This will package tls-xb in flake.nix so users can install tls-xb with nix.
=> Package tls-xb in flake.nix

src/main.rs
=> fix(login): prevent calling login twice when login

Cargo.lock, Cargo.toml, README.md, src/calendar.rs, src/config.rs, src/main.rs, src/semester.rs, src/subject.rs
=> Adds ical export

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md, flake-modules/treefmt.nix, flake.lock, flake.nix, src/calendar.rs, src/main.rs
Rewrites flake using flake-parts, fenix, and adds treefmt.
=> build: rewrite flake
